### ISSUE TITLE
[02 - JS and CSS Clock] Blblblblblb

### ISSUE THREAD

**Issue by brunowowk** [luanorlandi/javascript30#2]
Na mudança do minuto poderia rolar um Blblblblbl

**Comment by BrOrlandi** [comment]
Up!

**Comment by artureiji** [comment]
Up!

**Comment by notnotgabriel** [comment]
up kkkkk

**Comment by luanorlandi** [comment]
Commit  https://github.com/luanorlandi/javascript30/commit/19e5f57f6f73080ec6b4b946e48a4ecfc5d0ec2e :tada:
https://luanorlandi.github.io/javascript30/02-clock/index.html

![uinrlt6](https://user-images.githubusercontent.com/6919329/38646956-7139b03a-3dc0-11e8-90b5-22b69af7cfe5.gif)
